array_push(global.paper.columns, new column("Juney", [
"When it comes to making games, it's junejijo.",
"I tend to be the director as well as the writer for games our circle [BakaBaku] creates. I've also been responsible for programming (not really my preference) and graphics (which I've slowly started to improve on) when in a pinch on various BaBaCi projects. I have served as a writer, advisor and in a handful of unpublished instances, a voice actor for games outside of BaBaCi.",
"I think it's inevitable that a director will always want say in the writing because they're so emotionally attached to the message they're trying to send. I grew up with a cinematic arts and theater background, so I learned pretty early on that unity of vision is really very important when it comes to how to present any form of media. If there's any mis-step in the creative process between the writer and director, it really does reflect in the final cut. Just watch any movie-centric episode of Matt McMuscles' 'What Happened?' series or RedLetterMedia or even something like Mystery Science Theater 3000, and you'll notice how quickly things can unravel when it's clear the message and words don't mix. In terms of how easy it is, I would say it's harder than people might think. Because you have that much more investment in it, any decision which might get affected can feel like a personal attack, especially if it concerns a story feature. It can be hard to split that baby between the vision you want to put out into the world and the reality of your project. Ambition can often get in the way of completion-- a lesson I've learned and am still learning to this day.",
"The creative process I have is pretty scattered. I have a list of about two dozen ideas I've collected over three years ready to go at any time. These ideas tend to be single line phrases or more general observations/concepts or even just a funny tweet I saw I think would make for a good concept down the line. For this particular game, I actually took two ideas I had kinda put in the back of my brain and mashed them together into a single one. After that, it was just about finding a proper format. I have a reputation for producing visual novels, so this time I really wanted to challenge myself and make something unique that I thought was lacking in the Touhou Game Jam sphere. (I'm always chasing that one little innovation.) So in a break from my usual tradition, I asked some people from a lot of different social circles what might work for such a concept, got some feedback on it, did some research on that feedback, then decided on a handful of influences from there. The aesthetic of the game is also purposeful; it is meant to emulate the 20's and 30's, which was a very tumultuous time in American political and social history. Monopoly and old comics of the time were especially influential on our design due to the expression and ease, while we leaned on swing and ragtime for the music. It's one of my favorite eras to study back on (along with the Reconstruction era) and I think it's something that hasn't really been touched upon as far as designing a Touhou game.",
"Oh absolutely. I have always had a fascination with birds from the time I were a kid. I used to walk up to seagulls all the time to try and catch them, much to my mom's ire. Birds are really very cool animals, with lots of variety and a very complex way of life which makes them ceaselessly fascinating. There's big loon habitats near where I live and it's always fun to watch them move around unafraid of everything. In terms of the theme influencing the game, it did in that it allowed me to center a game on the bird tengus, which is something I've wanted to do for awhile now but never found a good opportunity for it. Aya was my first Touhou love and some of it is because of her being a crow, which is a kind of bird I love to bits.",
"I think I'd describe it as a cardinal. You think you know a cardinal, but in birding, the cardinal is one of the hardest birds to pin down. They have a great variety of plumages and can often be mistaken for similar birds. To tie it to the game, you might think you know what it is from the looks of it, but as you keep playing, you realize it might be more complex than anticipated. It's the same game, but it can go in so many different directions.",
"Ha, thanks! I enjoyed the talk!"

], ["What is your name?",
"From the outset, it seems like you're mainly a writer for game jam entries. Are there any other roles you also take on with game-making?",
"That's quite a lot! Directing and Writing seem like your two main roles. Do you feel being the writer of your games makes directing easier in some ways?",
"So in this mixed role, you've created a new game for this bird jam. What's your game about, and how have you shaped its vision?",
"The theme of birds is quite an unusual one. Were you already a fan of birds before you made the game, and how did the theme end up influencing your game?",
"If you had to describe your game as a species of bird, which would it be?",
"Alright. Thank you for your time! I hope readers will enjoy your 'cardinal'."
]));