function solaris_column(){
array_push(global.paper.columns, new column("Solaris", [
"Considering that my engine of choice is Ren'py I'd say that first and foremost I focus on having a good script and presentation. I think getting creative with audio and visuals really bring a story to life.",
"I'm Solaris. So I think it's worth noting that I probably wouldn't have any interest in game development if it weren't for Pokemon. I discovered the series at a really young age like many, and as I grew older I was quickly introduced to the ROM hacking scene for the series. I remember having ideas in my head about hacks I would want to create since I was like, 11 or so? creating a full scale hack is still a dream of mine, and I think that love for taking a series I enjoy and spinning it in my own directions was definitely responsible for me getting interested in joining these game jams. in fact it was Pokemon fangames that were responsible for getting into the Touhou series in the first place! and in Touhou I've found fantastic hyperfixation that, in a sea of yuri creations I love has also coincidentally kind of made me feel seen as an aromantic, just due to how open everything is in regards to relationships. ",
"this is a really interesting question, because I've found Ren'py as an engine to be incredibly easy to work with, so in a sense it's probably keeping my own anxiety in check so I can focus on script writing and programming, lol. everyone I've worked with on this game has been great, so, ultimately things fall on me as the director/producer and that gets a little bit scary at times! it's been a cool learning experience, though",
"god I've loved birds for as long as I can remember. I remember 5 year old me being absolutely enamored with falcons, which well, that's something that hasn't really changed? I still think birds of prey are really cool, even if they're also kinda terrifying. ultimately my favorite kind of bird is... very tough question for me, haha. I think in the moment I'd lean towards the Great Horned Owl, I just think they're really neat. also shoutouts to Bitterns, absolute funny little guys.",
"so my game is about an interview between Hatate and Satori, inspired by their interactions in the official manga kinda sticking with me after awhile. I wanted it to be an outlet to talk about some Cool Birds I Like, but also to talk about the anxiety of being a writer in one of my creations, since both Satori and Hatate are writers in canon, with very different focuses and experiences to share. I hope it's the kind of story that can resonate with at least someone. also in terms of birds, my inspirations came from the basis's of scrapped bird Pokemon designs. like for instance, the stork scrapped in Gen 2's development. it felt fitting for a Touhou work, and also absolutely the kind of nerdy stuff I love doing",
"so I've kind of thought about, and I think have a bit of an atypical answer to this. the Crested Ibis. for those who aren't familar with the story of the Crested Ibis. you see back in the 1980s, the species got absolutely decimated by things like overhunting, or the loss of their habitats, the increasing use of prestcides, the list... kind of goes on? they died out entirely in Japan's, and only had about a little over a 100 colonies in China. but there's a silver lining to this story, you see. found in 1967, the Sado Japanese Crested Ibis Conservation Center was born to help maintain the already lesser amounts of the species' population. China used their slightly rebounding wild population in the late 1990s to give a pair of Crested Ibis to this conversation center. they were allowed to comfortably breed, the chicks were widely celebrated, and 2008 some of the rebounding population was released into the wild. 2012 would come with the discovery that wild chicks were born for the first time 36 years, and as of now, while they're still endangered, Sado's population of them is over 500 now! it's an rare case of a conservation story gone right, and I think it's absolutely beautiful. and I think the kind of caring that produced that center, produced the other people who loved and celebrated this obscure bird, speaks well for the kind of thing that motivated this VN. we need people around us to thrive, and animals can be great friends for us in our darkest too. I want to tell a story that even if times look down for you, there can still be someone that can help you. just like the story of the Crested Ibis, in a distant way (jesus christ that became a whole essay LMAO).",
"yeah sure",
"you're welcome! this was fun. good luck with your project."
],
[
"What is your specialty when it comes to development? Are you a programmer? Do you focus on the presentation such as music or artwork? Or are you a renaissance man and just do a bit of everything?",
"Tell us a bit about yourself. Feel free to overshare to your heart's content.",
"What's the most difficult part of the game development process for you?",
"Would you consider yourself a fan of birds? What is your favorite, if you have any?",
"What is your game? What will it be like? What birds will the birders be able to expect?!",
"If you had to describe your game as a species of bird, which would it be?",
"(Do you want me to include the bottom line)",
"Alright that should be everything then. Thank you for your time."
]));
}