function citrus_column(){
array_push(global.paper.columns, new column("Citrus", [
"Every time I've worked in a team to develop a game, I tend to take on an administrative role. I manage the documents and delegate the roles, and then take care of the miscellaneous stuff that's not in the front and center. Sound effects, game descriptions, basic modeling, simple art, vague programming, and so on and so forth. I'm a very inexperienced jack-of-all-trades, somehow. My experience with developing small games extends a little bit past game jams, so in those areas, I'm also the person who presents a fair deal of the public image of those games in small circles. Recently I've been able to write a fair bit for projects like these which I've found really fun. ",
"I'm Citrus! If you've ever seen someone who really likes Kutaka Niwatari, then there's a good chance it's me. I was vaguely aware of Touhou before I properly explored it, but my deep dive started when the demo for Touhou 17 was released. I was recommended Kutaka's theme and clicked it because I like chickens. Clearly, that click led to a lot of other things.",
" I had floated around the community when Touhou 17 released, only watching gameplay and listening to the music. I somewhat explored the characters but had big misconceptions about them. I confused Junko and Okina, completely misunderstood the difference between Reisen and Manga Reisen, and I thought Iku was the antagonist of 12.3, stuff like that.As the Touhou 18 release cycle started with its announcement, I took the full plunge and started learning everything. I interacted with the community. I played (and still struggle) with the games. I explored the other Touhou media, official and fanwork. I had the full meal. And now here we are! Touhou has been a big part of my life since then, and I'm glad I've been able to have new experiences and inspirations because of it.",
],
[
"What is your specialty when it comes to development? Are you a programmer? Do you focus on the presentation such as music or artwork? Or are you a renaissance man and just do a bit of everything?",
"Tell us a bit about yourself. Feel free to overshare to your heart's content.",
"Tell us a bit about yourself Feel free to overshare to your heart's content. (cont.)"
]));

array_push(global.paper.columns, new column("Citrus (cont.)", [
"Well, initially, I would say starting the process at all. Motivation is a tough cookie for me, and I can only really get worked up when inspiration strikes, but beyond that, I feel like finding a way to manage your scope is key. I can say programming is my strongest weakness, but things like that are always skills that can be improved upon with practice. Scope is more unpredictable. You can have an idea and it can quickly grow out of hand by team input or ambition. Managing the times of the team, and the time that is given for development is important, and keeping the scope grounded leads to an easier timeline to follow. I find that when a team is allowed to be creative, but limited, they can work well. Maybe I focus on things like scope and timelines just because of my usual role, but like I said, skills I am personally weak in I can eventually improve (assuming I have the motivation to do so, haha).",
"I am a fan of birds! They're a coin flip between beautiful and interesting critters to just the silliest little guys around. Chickens of all breeds are something I love (though my liking for Kutaka was likely enough evidenced for that), but I am also a huge, huge fan of peacocks. So much so that when I was younger, I wrote a poem in elementary school about peacocks. I think it may be because there were some in my childhood zoo that roamed around, and I visited that zoo very often. If ZUN ever creates a peacock Touhou character, I think I may die from happiness.",
"Our game stars Kutaka! She's going to be frantically flying around trying to snatch up chickens as she protects her dear little friends from wolf spirits. It'll be a goofy game, with a squishy art style and silly sound effects, but we hope it's enjoyable! The birders will, naturally, be able to see chickens, but perhaps a shut-in crow tengu might make an appearance as well... Well, if we have time for that, of course.",
"The easy answer here is a chicken, but I would liken our game to a kiwi! Kiwis are odd little things, they’re flightless so they run around weirdly, look very squishable, and they make odd noises! And that sounds just like our gameplay! Our gameplay is near the ground in a top-down view, and involves quick movement, and I would like to think a kiwi perfectly encapsulates the silliness of birds, so I think that's a funny link to make. Alright, there's everything! Sorry if I was a bit wordy, I tend to be like that, haha. Thanks for the opportunity, and good luck with your game [newspaper]!"
],
[
"What's the most difficult part of the game development process for you?",
"Would you consider yourself a fan of birds? What is your favorite, if you have any?",
"What is your game? What will it be like? What birds will the birders be able to expect?!",
"If you had to describe your game as a species of bird, which would it be?"
]));
if not (array_contains(global.unlocks, "citrus")) array_push(global.unlocks, "citrus");
}